- .github/workflows/go.yml
- CLAUDE.md
- Activates the coverage option for the test command.
- Submits the coverage report to Codacy (requires a new repository secret that was added manually).
> test: Add coverage upload step to GitHub Action workflow

- .github/workflows/go.yml
As it was using glob to match, would ignore branches like fix/something
> fix: Run the action for all branches

- cmd/analyze.go
- tools/eslintRunner.go
- tools/eslintRunner_test.go
Before it would always output to SARIF if it would output to a file
> breaking: Control the output format with the format flag

- .codacy/cli-config.yaml
- cmd/init.go
- config/config.go
Also drops support for codacy.yml, as we control and create that file we pick the extension .yaml for our yaml files.
This PR only adds the file, there are other sub tasks to do the next steps
> Create cli configuration file PLUTO-1377

- README.md
- cmd/root.go
This pr is just to clarify the usage of cli in Readme, and just some nice formatting for the help command
> [PLUTO-1376] Improve readme/help command

- cmd/init.go
if token is provided provider, organization and repository are not optional.
> improve init message 

- .codacy/codacy.yaml
- cmd/analyze.go
- plugins/tool-utils_test.go
- plugins/tools/semgrep/plugin.yaml
- tools/runnerUtils.go
- tools/semgrepRunner.go
- tools/semgrepRunner_test.go
- tools/testdata/repositories/semgrep/expected.sarif
- tools/testdata/repositories/semgrep/sample.js
⚠️ PR to feature branch 
config init will be added in another PR
> Pluto 1390 semgrep installation and running

- cmd/analyze.go
- tools/eslintRunner.go
- tools/pmdRunner.go
- tools/pylintRunner.go
- tools/trivyRunner.go
- utils/sarif.go
This pull request includes several changes to improve error handling in the analysis tools and ensure that errors are properly propagated and logged. The most important changes include modifying the analysis functions to return errors, updating the `runTool` function to handle these errors, and adding error handling in the tool runners.
Error handling improvements:
* [`cmd/analyze.go`](diffhunk://#diff-4d578b2f3d178fd7a93e4c290082b78ed6f70f5c3e99dd31c42d1a124f7346dfL191-R217): Modified `runEslintAnalysis`, `runTrivyAnalysis`, `runPmdAnalysis`, and `runPylintAnalysis` functions to return errors instead of logging fatal errors directly. Updated `runTool` function to handle these errors and log appropriate messages. [[1]](diffhunk://#diff-4d578b2f3d178fd7a93e4c290082b78ed6f70f5c3e99dd31c42d1a …
> [PLUTO-1396] Handle tool errors gracefully

- config/config.go
If codacy.yml already exists, rely on it, otherwise rely on codacy.yaml
This check existed in the past, but got removed as we control the configuration file.
However, as a request from @heliocodacy due to users already using that format from the previous version of the CLI, we are restoring it
> feature: Adds support for codacy.yml

- cmd/init.go
- tools/eslintConfigCreator.go
- tools/eslintConfigCreator_test.go
When running ESLint without a local configuration file, handling ESLint plugins (especially with ESLint 8) has proven to be challenging due to:
1. Complex plugin resolution and loading mechanisms in ESLint 8
2. Difficulties in managing plugin dependencies and their peer dependencies
3. Potential conflicts between different plugin versions
4. Increased complexity in maintaining a reliable plugin ecosystem across different environments
As a temporary solution, this PR modifies the ESLint configuration generator to:
- Skip all plugin rules (rules containing "/") when generating the configuration
- Only process core ESLint rules
- Keep all existing functionality for core rules including parameters and error levels
This change ensures more reliable ESLint analysis when running without local …
> avoiding eslint plugins - PLUTO-1364

- .codacy/codacy.yaml
- cmd/init.go
- go.mod
- go.sum
- tools/eslintRunner_test.go
- tools/language_config.go
- tools/language_config_test.go
- tools/testdata/repositories/test1/expected.sarif
- tools/testdata/repositories/test1/src/testdata/repositories/test1/eslint.sarif
- tools/testdata/repositories/test1/src/testdata/repositories/test1/expected.sarif
- tools/testdata/repositories/test1/src/testdata/repositories/test1/sarif.json
This PR implements the integration with Codacy's API to fetch and use repository language information for tool configuration. It creates a `languages-config.yaml` file that maps tools to their supported languages based on what's detected in the repository.
- Fetches repository language information from Codacy API endpoint
- Creates a mapping between tools and their supported languages/extensions
- Generates `languages-config.yaml` based on the API response
- Special handling for multi-language tools like Trivy
1. Languages are only included when **both** conditions are met:
- `enabled: true` - Language is enabled in Codacy settings
- `detected: true` - Language is actually detected in the repository
2. Extensions are a **union** of:
- `codacyDefaults` - Default extensions provided by …
> feature: using API repo languages to create languages-config file - PLUTO-1402

- .github/workflows/go.yml
- .github/workflows/it-test.yml
- Makefile
- cli-v2.go
- cmd/root.go
- cmd/root_test.go
- cmd/version.go
- version/version.go
Showing information on `version` command 
```
Codacy CLI Version Information
-----------------------------
Version:    1.0.0-main.289.5448b24-dirty
Commit:     5448b24
Built:      2025-05-12_14:31:19
Go version: go1.24.1
OS/Arch:    darwin/amd64
```
feature: add version command and enhance CLI logging
- Add version command to display CLI version information
- Add command execution logging with sensitive data masking
- Add version logging to file
> feature: Add version command

- .github/workflows/go.yml
- .goreleaser.yaml
fix: version passing to GoReleaser configuration 
Fix version command by properly configuring GoReleaser and version injection:
- Update GoReleaser to use version constraint (~> v1) instead of 'latest'
- Fix version information injection through ldflags
- Add proper environment variable handling for Go version
This ensures the version command shows correct build information
and follows GoReleaser's best practices for version constraints.
> Fix: version passing to GoReleaser configuration

- tools/dartanalyzerRunner.go
- tools/enigmaRunner.go
- tools/semgrepRunner.go
- utils/sarif.go
When semgrep is run with --sarif flag, it adds all rules to output (there is no flag to suppress this ).
This causing our output file to be like 30K lines (for the project I tested) when we have zero findings ⚠️ 
- Updated logging in dartanalyzerRunner.go and enigmaRunner.go to use log.Println instead of fmt.Println for better log management.
- Enhanced semgrepRunner.go to include SARIF output processing, filtering rule definitions, and writing filtered results to specified output files.
> fix: semgrep sarif to not put all rules in output

- cmd/init.go
- cmd/init_test.go
- codacy-client/client.go
- codacy-client/client_test.go
- domain/initFlags.go
- domain/pagination.go
- domain/patternConfiguration.go
This PR introduces two main improvements:
1. Use Codacy's default patterns for each tool when no API token is provided
2. Add new endpoint in `codacy-client` package to fetch patterns for supported tools
- When initializing without an API token, the CLI now fetches and uses Codacy's default patterns for each tool
- This ensures consistent behavior across all installations, even in local mode
- Default patterns are fetched from Codacy's API and stored in the local configuration
- Affects all supported tools: ESLint, PMD, Pylint, Trivy, DartAnalyzer, etc.
- Added new `GetDefaultToolPatternsConfig` function in `codacy-client` package
- This endpoint handles fetching patterns for any supported tool
- Implemented generic pagination handling for consistent API response processing
- Note: This …
> feature: fetch codacy default values for all tools patterns when no token init - PLUTO-1380

- README.md
- cmd/init.go
- cmd/init_test.go
- cmd/root.go
- integration-tests/init-without-token/expected/codacy.yaml
- tools/eslintConfigCreator.go
- tools/eslintConfigCreator_test.go
- Fixed handling of named parameters in ESLint rules configuration
- Added support for using default values when parameter values are empty
- Properly formatted boolean parameters (true/false) without quotes
- Ensured all rules use consistent array format `["error", ...]` instead of mixing formats
- Fixed issue where parameters with empty values were incorrectly ignored even when defaults existed
- More accurate and consistent ESLint configurations
- Rules now correctly apply their intended parameters
- Better handling of empty values by using defined defaults
- Improved compatibility with ESLint 8.57.0 which is currently supported in CLI
> fix eslint config creation and using default 8.57.0 instead 9.3.0 (when init without token)

- tools/pmdConfigCreator.go
- tools/pmdConfigCreator_test.go
The PMD configuration generator was incorrectly handling parameter values, resulting in empty or missing properties in the generated XML configuration. Rules that should have included property values were being output without their required properties.
**Before Fix (incorrect output):**
```xml
<rule ref="category/pom/errorprone.xml/InvalidDependencyTypes"/>
```
**After Fix (correct output with properties):**
```xml
<rule ref="category/pom/errorprone.xml/InvalidDependencyTypes">
<properties>
<property name="validTypes" value="pom,jar,maven-plugin,ejb,war,ear,rar,par"/>
</properties>
</rule>
```
- Modified the parameter value handling to correctly use default values when the explicitly specified value is empty
- Ensured property values are properly included in the generated XML …
> fix: PMD Parameter Value Parsing

- utils/logger/logger.go
Previously, log messages showed internal logger locations (e.g. logrus/entry.go:304) instead of the actual source file where the logging occurred.
Before: 
```
2025-05-27T11:49:41+02:00 [INFO] (utils/logger/logger.go:106) Starting Codacy CLI version=development
2025-05-27T11:49:41+02:00 [INFO] (utils/logger/logger.go:106) Executing CLI command full_command=[/Users/czak/Library/Caches/go-build/9c/9caf9ed9717356d0eed8d1ab8ee099d839c3e5306340732eb8232ae2792d62e7-d/cli-v2 init] args=[] command=init
2025-05-27T15:32:48+02:00 [INFO] (utils/logger/logger.go:106) Starting Codacy CLI version=development
2025-05-27T15:32:48+02:00 [INFO] (utils/logger/logger.go:106) Executing CLI command args=[] command=init full_command=[/Users/czak/Library/Caches/go-build/9c/9caf9ed9717356d0eed8d1ab8ee099d839c3e530 …
```
> fix: show actual source file location in logs instead of logger internals

- cmd/analyze.go
- cmd/init.go
- cmd/init_test.go
- domain/tool.go
- integration-tests/init-with-token/expected/tools-configs/ruleset.xml
- integration-tests/init-without-token/expected/codacy.yaml
- integration-tests/init-without-token/expected/tools-configs/ruleset.xml
- integration-tests/run.ps1
- integration-tests/run.sh
- plugins/tools/eslint/plugin.yaml
- plugins/tools/pmd/plugin.yaml
- tools/eslintConfigCreator.go
- tools/getTools.go
- tools/pmdConfigCreator.go
- tools/pmdConfigCreator_test.go
- tools/pmdRunner.go
example init: 
```
⚠️  Multiple versions of 'pmd' detected: [6.55.0, 7.11.0], keeping 7.11.0
⚠️  Multiple versions of 'eslint' detected: [9.26.0, 8.57.0], keeping 9.26.0
Created languages configuration file based on enabled tools
PMD7 configuration created based on Codacy settings
ESLint configuration created based on Codacy settings. Ignoring plugin rules. ESLint plugins are not supported yet.
```
> [PLUTO-1395] Handle multiple pmd/eslint versions

- README.md
- cli-v2.go
- cmd/cmdutils/flags.go
- cmd/config.go
- cmd/configsetup/setup.go
- cmd/init.go
- cmd/root.go
- cmd/validation.go
- config/detector.go
- tools/language_config.go
New `config discover` command that automatically detects programming languages in a project and configures appropriate static analysis tools.
```bash
codacy-cli config discover <path>
```
- Scans directory for file extensions
- Maps extensions to programming languages
- Updates `languages-config.yaml` and `codacy.yaml`
- Enables relevant tools (pylint, eslint, pmd, etc.)
- Creates tool-specific configuration files
- **New**: `config/detector.go` - language detection logic
- **New**: `cmd/validation.go` - enhanced validation
- **Modified**: `cmd/config.go` - discover command implementation
- **Fixed**: Added missing `GetDefaultToolLanguageMapping()` function in `tools/language_config.go`
- Automatic project setup
- Reduces manual configuration
- Ensures comprehensive tool coverage
- Works …
> Feature: config discover command 

- cmd/analyze.go
- cmd/analyze_test.go
- integration-tests/init-with-token/expected/tools-configs/lizard.yaml
- integration-tests/init-without-token/expected/tools-configs/lizard.yaml
- plugins/tools/trivy/test/expected.sarif
- utils/sarif.go
Now:
```
go run cli-v2.go  analyze --format sarif ./what
❌ Error: cannot find file or directory './what'
exit status 1
```
Before: 
```
2025/06/11 14:28:37 Failed to merge SARIF outputs: failed to parse SARIF file /tmp/codacy-analysis-2905944739/semgrep.sarif: unexpected end of JSON input
``` 
* this PR include it tests update
> Fix: CLI failes when running with non exsisting file  

- cmd/root.go
- cmd/validation.go
- Changed the check from the existence of the .codacy directory to the codacy.yaml file.
- Updated the welcome message to provide clearer instructions for initializing with a Codacy account.
- Added "update" command to the list of commands that can skip validation.
- Improved overall clarity and user guidance in the CLI output.
> fix: Update welcome message and command validation

- .gitignore
- tools/trivyConfigCreator.go
- tools/trivyConfigCreator_test.go
adds trivy new patterns, high and critical, config mappings  CF-1860
> feature: trivy new patterns config mappings CF-1860

- cmd/upload.go
- plugins/tool-utils.go
- plugins/tool-utils_test.go
- plugins/tools/trivy/plugin.yaml
Only sending sourceId fror Trivy will avoid messing with the results from other tools and respects on how codacy cloud and the CLI v1 handles it.
The downside is that will be a bit error prone when adding other tools that 'need it' like Prospector, if forget to add it, less results will be added on Codacy, it will be kinda easy to identify, but can lead to that. For now it is an acceptable compromise.
Note on diff coverage, changes on the upload.go not covered, and doing tests for the upload will not happen on this scope.
> feature: Upload sourceId when available from SARIF CF-1813
